FROM gliderlabs/alpine:3.1

ENV HOST_NAME middleman

RUN apk-install nginx \
  && mkdir -p /tmp/nginx

EXPOSE 8000

COPY nginx.conf /etc/nginx/nginx.conf

ADD build.tar.gz /usr/src/app/

# Figure out root cause of middleman permissions
RUN chmod -R a+r /usr/src/app/build

CMD nginx
